version: '3'
services:
    app:
        container_name: go-team
        image: golang:1.15
        working_dir: "/data"
        ports:
            - "8000:8000"
        volumes:
            - ./:/data
            - ./.env-docker:/data/.env
        links:
            - db:db
        command: sh -c "go run main.go"

    db:
        image: "postgres:11"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data

        environment:
            POSTGRES_USER: goteam
            POSTGRES_PASSWORD: goteam
            POSTGRES_DB: goteam
